
name: Build Docker exsi Image and Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image for amd64
        run: |
          docker buildx build --platform linux/amd64 -t exsi:amd64 --load .

      - name: Save Docker image as tar for amd64
        run: |
          docker save r2:amd64 -o exsi_amd64.tar
      
      
      - name: Upload Docker image artifacts
        uses: actions/upload-artifact@v4
        with:
          name: exsi_images
          path: |
            exsi_amd64.tar
